import type { Issue, IssueProject } from "./types";

const daysAgo = (days: number) =>
  new Date(Date.now() - days * 24 * 60 * 60 * 1000).toISOString();

const daysFromNow = (days: number) =>
  new Date(Date.now() + days * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);

export const issueProjects: IssueProject[] = [
  { id: "p1", key: "WR", name: "Website Redesign" },
  { id: "p2", key: "MA", name: "Mobile App" },
  { id: "p3", key: "CS", name: "CRM System" },
];

export const issueAssignees = [
  "Admin User",
  "Sarah Chen",
  "Marcus Lee",
  "Priya Patel",
  "James Okonkwo",
];

export const mockIssues: Issue[] = [
  {
    id: "issue-1",
    key: "WR-101",
    title: "Login page UI broken",
    description: "The login form overlaps the illustration on smaller laptops.",
    type: "Bug",
    status: "To Do",
    priority: "High",
    assignee: "Marcus Lee",
    reporter: "James Okonkwo",
    project: "Website Redesign",
    sprint: "sprint-1",
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0),
    dueDate: daysFromNow(3),
  },
  {
    id: "issue-2",
    key: "WR-102",
    title: "Implement authentication",
    description: "Wire login, register, and protected routes to local auth.",
    type: "Feature",
    status: "In Progress",
    priority: "Highest",
    assignee: "Admin User",
    reporter: "James Okonkwo",
    project: "Website Redesign",
    sprint: "sprint-1",
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
    dueDate: daysFromNow(5),
  },
  {
    id: "issue-3",
    key: "WR-103",
    title: "Fix sidebar responsiveness",
    description: "Sidebar should collapse cleanly on tablet widths.",
    type: "Task",
    status: "Done",
    priority: "Medium",
    assignee: "Sarah Chen",
    reporter: "Admin User",
    project: "Website Redesign",
    sprint: "sprint-2",
    createdAt: daysAgo(12),
    updatedAt: daysAgo(2),
    dueDate: daysFromNow(-1),
  },
  {
    id: "issue-4",
    key: "MA-104",
    title: "Error on issue create",
    description: "Creating an issue without an assignee throws a null error.",
    type: "Bug",
    status: "To Do",
    priority: "High",
    assignee: "Priya Patel",
    reporter: "Sarah Chen",
    project: "Mobile App",
    sprint: "sprint-2",
    createdAt: daysAgo(5),
    updatedAt: daysAgo(3),
    dueDate: daysFromNow(4),
  },
  {
    id: "issue-5",
    key: "MA-105",
    title: "Add loader component",
    description: "Shared spinner for list and detail fetches.",
    type: "Task",
    status: "In Progress",
    priority: "Low",
    assignee: "Admin User",
    reporter: "Sarah Chen",
    project: "Mobile App",
    sprint: "sprint-1",
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    dueDate: daysFromNow(7),
  },
  {
    id: "issue-6",
    key: "CS-201",
    title: "Customer timeline epic",
    description: "All work related to the account activity timeline.",
    type: "Epic",
    status: "Backlog",
    priority: "Medium",
    assignee: "James Okonkwo",
    reporter: "James Okonkwo",
    project: "CRM System",
    sprint: null,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(10),
    dueDate: daysFromNow(30),
  },
  {
    id: "issue-7",
    key: "CS-202",
    title: "Export contacts as CSV",
    description: "Allow managers to download the filtered contact list.",
    type: "Story",
    status: "Backlog",
    priority: "Medium",
    assignee: "Sarah Chen",
    reporter: "James Okonkwo",
    project: "CRM System",
    sprint: null,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(9),
    dueDate: daysFromNow(14),
  },
  {
    id: "issue-8",
    key: "WR-106",
    title: "Empty state for boards",
    description: "Show a friendly empty column when a status has no issues.",
    type: "Task",
    status: "Backlog",
    priority: "Low",
    assignee: null,
    reporter: "Admin User",
    project: "Website Redesign",
    sprint: null,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    dueDate: null,
  },
  {
    id: "issue-9",
    key: "MA-107",
    title: "Push notification opt-in",
    description: "Ask users for notification permission after first board visit.",
    type: "Story",
    status: "Done",
    priority: "Medium",
    assignee: "Sarah Chen",
    reporter: "Admin User",
    project: "Mobile App",
    sprint: null,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
    dueDate: daysFromNow(-3),
  },
  {
    id: "issue-10",
    key: "CS-203",
    title: "Duplicate company records",
    description: "Merging two companies with the same domain fails silently.",
    type: "Bug",
    status: "In Review",
    priority: "Highest",
    assignee: "Priya Patel",
    reporter: "James Okonkwo",
    project: "CRM System",
    sprint: "sprint-2",
    createdAt: daysAgo(3),
    updatedAt: daysAgo(0),
    dueDate: daysFromNow(2),
  },
];
