import type { Person } from "./types";

export const mockPeople: Person[] = [
  {
    id: "person-1",
    name: "Admin User",
    email: "admin@example.com",
    avatar: "#7c3aed",
    role: "Admin",
    department: "Engineering",
    active: true,
    assignedIssues: [
      {
        id: "pi-1",
        key: "WR-102",
        title: "Implement authentication",
        type: "Feature",
        status: "In Progress",
        priority: "Highest",
        project: "Website Redesign",
      },
      {
        id: "pi-2",
        key: "MA-105",
        title: "Add loader component",
        type: "Task",
        status: "In Progress",
        priority: "Low",
        project: "Mobile App",
      },
    ],
    projects: [
      { id: "pp-1", key: "WR", name: "Website Redesign", role: "Admin" },
      { id: "pp-2", key: "MA", name: "Mobile App", role: "Contributor" },
      { id: "pp-3", key: "CS", name: "CRM System", role: "Contributor" },
    ],
  },
  {
    id: "person-2",
    name: "Sarah Chen",
    email: "sarah.chen@example.com",
    avatar: "#2563eb",
    role: "Project Lead",
    department: "Engineering",
    active: true,
    assignedIssues: [
      {
        id: "pi-3",
        key: "WR-103",
        title: "Fix sidebar responsiveness",
        type: "Task",
        status: "Done",
        priority: "Medium",
        project: "Website Redesign",
      },
      {
        id: "pi-4",
        key: "CS-202",
        title: "Export contacts as CSV",
        type: "Story",
        status: "Backlog",
        priority: "Medium",
        project: "CRM System",
      },
      {
        id: "pi-5",
        key: "MA-107",
        title: "Push notification opt-in",
        type: "Story",
        status: "Done",
        priority: "Medium",
        project: "Mobile App",
      },
    ],
    projects: [
      { id: "pp-4", key: "MA", name: "Mobile App", role: "Lead" },
      { id: "pp-5", key: "WR", name: "Website Redesign", role: "Contributor" },
    ],
  },
  {
    id: "person-3",
    name: "Marcus Lee",
    email: "marcus.lee@example.com",
    avatar: "#0d9488",
    role: "Developer",
    department: "Engineering",
    active: true,
    assignedIssues: [
      {
        id: "pi-6",
        key: "WR-101",
        title: "Login page UI broken",
        type: "Bug",
        status: "To Do",
        priority: "High",
        project: "Website Redesign",
      },
    ],
    projects: [
      { id: "pp-6", key: "WR", name: "Website Redesign", role: "Developer" },
      { id: "pp-7", key: "MK", name: "Launch Campaign", role: "Lead" },
    ],
  },
  {
    id: "person-4",
    name: "Priya Patel",
    email: "priya.patel@example.com",
    avatar: "#db2777",
    role: "Designer",
    department: "Design",
    active: true,
    assignedIssues: [
      {
        id: "pi-7",
        key: "MA-104",
        title: "Error on issue create",
        type: "Bug",
        status: "To Do",
        priority: "High",
        project: "Mobile App",
      },
      {
        id: "pi-8",
        key: "CS-203",
        title: "Duplicate company records",
        type: "Bug",
        status: "In Review",
        priority: "Highest",
        project: "CRM System",
      },
    ],
    projects: [
      { id: "pp-8", key: "MA", name: "Mobile App", role: "Designer" },
      { id: "pp-9", key: "CS", name: "CRM System", role: "Contributor" },
    ],
  },
  {
    id: "person-5",
    name: "James Okonkwo",
    email: "james.okonkwo@example.com",
    avatar: "#ea580c",
    role: "Project Lead",
    department: "Product",
    active: true,
    assignedIssues: [
      {
        id: "pi-9",
        key: "CS-201",
        title: "Customer timeline epic",
        type: "Epic",
        status: "Backlog",
        priority: "Medium",
        project: "CRM System",
      },
    ],
    projects: [
      { id: "pp-10", key: "CS", name: "CRM System", role: "Lead" },
      { id: "pp-11", key: "MK", name: "Launch Campaign", role: "Stakeholder" },
    ],
  },
  {
    id: "person-6",
    name: "Elena Rossi",
    email: "elena.rossi@example.com",
    avatar: "#d97706",
    role: "QA",
    department: "Engineering",
    active: true,
    assignedIssues: [
      {
        id: "pi-10",
        key: "WR-108",
        title: "Regression on password reset",
        type: "Bug",
        status: "In Review",
        priority: "High",
        project: "Website Redesign",
      },
      {
        id: "pi-11",
        key: "MA-110",
        title: "Smoke test release candidate",
        type: "Task",
        status: "To Do",
        priority: "Medium",
        project: "Mobile App",
      },
    ],
    projects: [
      { id: "pp-12", key: "WR", name: "Website Redesign", role: "QA" },
      { id: "pp-13", key: "MA", name: "Mobile App", role: "QA" },
    ],
  },
  {
    id: "person-7",
    name: "Tom Nguyen",
    email: "tom.nguyen@example.com",
    avatar: "#64748b",
    role: "Developer",
    department: "Engineering",
    active: false,
    assignedIssues: [],
    projects: [{ id: "pp-14", key: "MA", name: "Mobile App", role: "Developer" }],
  },
  {
    id: "person-8",
    name: "Aisha Rahman",
    email: "aisha.rahman@example.com",
    avatar: "#16a34a",
    role: "Designer",
    department: "Marketing",
    active: true,
    assignedIssues: [
      {
        id: "pi-12",
        key: "MK-301",
        title: "Landing page hero illustrations",
        type: "Task",
        status: "In Progress",
        priority: "High",
        project: "Launch Campaign",
      },
    ],
    projects: [
      { id: "pp-15", key: "MK", name: "Launch Campaign", role: "Designer" },
    ],
  },
  {
    id: "person-9",
    name: "Noah Williams",
    email: "noah.williams@example.com",
    avatar: "#6b7280",
    role: "Viewer",
    department: "Support",
    active: true,
    assignedIssues: [],
    projects: [{ id: "pp-16", key: "CS", name: "CRM System", role: "Viewer" }],
  },
];
